### PR TITLE
Fix broken JSX option checks

### LINKED ISSUE #1816: Assertion failed at transformJsxTagNameExpression when using custom jsxfactory.
# Problem
When trying to make something similar to Roact, I encountered a compiler bug that only happens with jsx declarations.
## Error
```
Error: Assertion Failed!
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformJsxTagNameExpression (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:18:33)
    at C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:36:55
    at C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:108:60
    at TransformState.capturePrereqs (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:103:9)
    at TransformState.capture (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:108:30)
    at transformJsxTagName (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:36:41)
    at transformJsx (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsx.js:22:84)
    at transformJsxSelfClosingElement (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformJsxSelfClosingElement.js:6:44)
    at transformExpression (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
```

## Reproduction
1. In a new folder do ``` rbxtsc init package ```
2. Accept all prompts
3. Delete everything under /src and /out
4. Set ``` "jsxFactory" ``` to ``` Luck.createElement ``` in tsconfig.json
5. Under /src add the following files:
### createElement.ts
```typescript
export function createElement<T extends keyof CreatableInstances = keyof CreatableInstances>(
	tag: T,
	attributes: { [key in keyof CreatableInstances[T]]?: CreatableInstances[T][key] },
	...children: Instance[]
) {
	const element = new Instance(tag);

	// append children
	children.forEach((child) => {
		child.Parent = element;
	});
	return element;
}
```
### index.d.ts
```typescript
import { createElement } from "./createElement";
declare namespace Luck {
	export { createElement };
}

declare global {
	namespace JSX {
		type IntrinsicElementsMap = {
			part: {
				[key in keyof Part]?: Part[key];
			};
		};
		interface IntrinsicElements extends IntrinsicElementsMap {}
	}
}
```
### test.tsx
```typescript
import { Luck } from "./index";
<part />;
```
6. run ```npm run build```

### PR DESCRIPTION
**Pull request by Dionysusnu**
Fixes #1816

### CODE REVIEW

**Comment by vendkita** [comment]
When using a custom jsxFactory function, this error occurs on ``` rbxtsc  -w ```:
```
Project Error: Invalid "tsconfig.json" configuration!
https://roblox-ts.github.io/docs/quick-start#project-folder-setup
- "jsxFactory" must be "Roact.createElement" or not defined  
```
I believe this to be an error, because these commits are aimed towards custom jsxFactory functions.

**Comment by vendkita** [comment]
Fixed factory and fragment factory mix-up in #1818

File: src/TSTransformer/classes/MultiTransformState.ts [hunk 1]
```diff
@@ -13,18 +13,26 @@ export class MultiTransformState {
 	public readonly getModuleExportsAliasMapCache = new Map<ts.Symbol, Map<ts.Symbol, string>>();
 
 	public hasCheckedJsxFactory = false;
-	public checkJsxFactory(node: ts.Node, compilerOptions: ts.CompilerOptions) {
-		this.hasCheckedJsxFactory = true;
-		if (!this.hasCheckedJsxFactory && compilerOptions.jsxFactory !== "Roact.createElement") {
-			DiagnosticService.addDiagnostic(errors.invalidJsxFactory(node));
+	public isRoactJsxFactory(node: ts.Node, compilerOptions: ts.CompilerOptions) {
```
Comment (osyrisrblx) [inline src/TSTransformer/classes/MultiTransformState.ts:16]: I think I prefer the original `check-` prefix here.

An `is-` prefix indicates to me that a function checks the status of something (and probably returns a boolean) without side effects.

File: src/TSTransformer/classes/TransformState.ts [hunk 2]
```diff
@@ -200,11 +200,11 @@ export class TransformState {
 		return luau.property(luau.globals.TS, name);
 	}
 
-	public checkJsxFactory(node: ts.Node) {
-		this.multiTransformState.checkJsxFactory(node, this.compilerOptions);
+	public isRoactJsxFactory(node: ts.Node) {
```
Comment (osyrisrblx) [inline src/TSTransformer/classes/TransformState.ts:203]: Maybe we should just invoke the MultiTransformState method directly instead of having these proxy functions?

File: src/TSTransformer/classes/MultiTransformState.ts (hunk 1 above)
Comment (Dionysusnu) [reply src/TSTransformer/classes/MultiTransformState.ts:16]: Then again, check implies it does not return anything. maybe `checkIsRoactJsxFactory`?

File: src/TSTransformer/classes/TransformState.ts (hunk 2 above)
Comment (Dionysusnu) [reply src/TSTransformer/classes/TransformState.ts:203]: I feel like this adds more duplication, because of passing compilerOptions. it's not great though :/

Comment (osyrisrblx) [reply src/TSTransformer/classes/TransformState.ts:203]: We could give CompilerOptions to MultiTransformState in it's constructor

Comment (Dionysusnu) [reply src/TSTransformer/classes/TransformState.ts:203]: That would be duplicating the object/reference. But I guess it's immutable so that's fine?

Comment (Dionysusnu) [reply src/TSTransformer/classes/TransformState.ts:203]: Now that I think about it, it could also use the new `addDiagnosticFromNodeIfNotCached`. No transformstate call necessary
