### PR TITLE
Fix this: void incorrect emit

### LINKED ISSUE #645: Function compiles with colon when using this: void
Function is compiled incorrectly (with a colon), but is called correctly (with a dot).

## Playground link
[Link here](https://roblox-ts.github.io/playground/#code/MYewdgzgLgBCBGArGBeGBvAUDHMAmIAyiALYCmUAFgJZgDmMAFFdRAFwwBuI1eAlBkzZcAX0xjMCRADoCxci3qM+QA).

### PR DESCRIPTION
**Pull request by evaera**
Fix #645

### CODE REVIEW

**Comment by evaera** [comment]
`isMethodDeclaration` should take care of de-duplicating the checks for `this: void` since it's checked within there, so I removed the explicit checks in `allMethods` and `allCallbacks`. This seems to work on the surface level but it's causing some of the tests to trigger with mixed call errors.

File: src/compiler/function.ts [hunk 1]
```diff
@@ -78,10 +78,17 @@ export function isFunctionExpressionMethod(node: ts.FunctionExpression) {
 }
 
 export function isMethodDeclaration(node: ts.Node<ts.ts.Node>): node is ts.MethodDeclaration | ts.FunctionExpression {
-	return (
+	if (
+		ts.TypeGuards.isMethodSignature(node) ||
```
Comment (evaera) [inline src/compiler/function.ts]: This was the culprit. Added this because declared methods weren't being seen as methods. I'm guessing that this is fine?
