### PR TITLE
enforce minimum rbx-types version

### LINKED ISSUE #239: Specify minimum rbx-types version with compiler releases and inspect dependencies to ensure compatability
This could work by comparing semver strings. Wrong rbx-types version can lead to unexpected bugs for beginners or anyone who just forgets to update. This will help bring the problem to the user's attention more clearly.

### PR DESCRIPTION
**Pull request by osyrisrblx**
Closes #239

### CODE REVIEW

File: src/Project.ts [hunk 1]
```diff
@@ -280,6 +283,45 @@ export class Project {
...
+							if (regexMatch !== null) {
+								const patchNumber = Number(regexMatch[0]);
+								if (!isNaN(patchNumber)) {
+									if (patchNumber >= MINIMUM_RBX_TYPES_VERSION) {
+										return;
+									} else {
+										throw new ProjectError(
+											`rbx-types is out of date!\n` +
+												yellow(`Installed version: ${rbxTypesVersion}\n`) +
+												yellow(`Minimum required version: 1.0.${MINIMUM_RBX_TYPES_VERSION}\n`) +
```
Comment (Validark) [inline src/Project.ts]: I don't necessarily like that it only allows versions which begin with `1.0.`. Are we going to have to "fix" this in the future due to an update?

Comment (Validark) [reply src/Project.ts]: image

File: src/Project.ts [hunk 2]
```diff
@@ -280,6 +283,45 @@ export class Project {
...
+								}
+							}
+						}
+					}
+				}
+			}
+		}
+		throw new ProjectError(
+			"Could not find rbx-types in package-lock.json! Is rbx-types installed?",
+			ProjectErrorType.BadRbxTypes,
```
Comment (Validark) [inline src/Project.ts]: Could we suggest to run `npm i rbx-types`?
