### PR TITLE
Fix #380

### LINKED ISSUE #380: Destructuring from TS.Symbol_Iterator or an IterableFunction is broken
Description here:
https://github.com/roblox-ts/roblox-ts/blob/98d1c79c054fd07f67eb1d334bfeb18d07d3eaea/src/compiler/binding.ts#L186-L203

### PR DESCRIPTION
**Pull request by osyrisrblx**

### CODE REVIEW

File: src/compiler/variable.ts [hunk 1]
```diff
@@ -107,12 +119,28 @@ export function compileVariableDeclaration(state: CompilerState, node: ts.Variab
...
 		}
 
+		if (ts.TypeGuards.isArrayBindingPattern(lhs)) {
+			const rhsType = rhs.getType();
+			if (
+				!isArrayType(rhsType) &&
+				!isIterableIterator(rhsType, rhs) &&
+				!isIterableFunction(rhsType) &&
+				(isObjectType(rhsType) || ts.TypeGuards.isThisExpression(rhs))
+			) {
```
Comment (Validark) [inline src/compiler/variable.ts]: This should have !isMapType && !isSetType

**Comment by Validark** [comment]
This PR should address this issue here: https://github.com/roblox-ts/roblox-ts/issues/369

I recommend making an `isTupleType` function in typeUtilities.ts
```ts
export function isTupleType(node: ts.TypeNode | ts.Type) {
	return /^LuaTuple<[^]+>$/.test(node.getText());
}

export function isTupleReturnType(node: ts.ReturnTypedNode) {
	const returnTypeNode = node.getReturnTypeNode();
	return returnTypeNode ? isTupleType(returnTypeNode) : false;
}
```

This also means you will need to add it to the logic in variable.ts:
```ts
if (
	!isTupleType(rhsType) &&
	!isArrayType(rhsType) &&
	!isMapType(rhsType) &&
	!isSetType(rhsType) &&
	!isIterableIterator(rhsType, rhs) &&
	!isIterableFunction(rhsType) &&
	(isObjectType(rhsType) || ts.TypeGuards.isThisExpression(rhs))
) {
```
And, of course, add it to binding.ts
```ts
export function getAccessorForBindingPatternType(bindingPattern: ts.Node) {
	const bindingPatternType = bindingPattern.getType();
	if (isTupleType(bindingPatternType)) {
		return tupleAccessor;
```
